export const projects = [
  {
    title: "mtindo",
    description:
      "mtindo is a style transfer application. It offers a unique opportunity that generates a new image/video from an image/video.",
    image: "/images/mtindo.webp",
    tags: ["python", "nodejs", "electron"],
    source: "",
    visit: "https://itp.nyu.edu/thesis2018/#/student/koji",
    id: 0,
  },
  {
    title: "Data from Mukuru",
    description:
      "Data Visualization project with Pawa Initiative which is a NPO in Nairobi, Kenya.",
    image: "/images/data-from.webp",
    tags: ["js", "D3js", "heroku"],
    source: "",
    visit: "http://datavi.herokuapp.com/mukuru/",
    id: 1,
  },
  {
    title: "nikobot",
    description:
      "nikobot is an interactive expressive robot pet for your desk, a minimal interactive robot.",
    image: "/images/nikobot.webp",
    tags: ["Arduino", "html", "css", "js"],
    source: "",
    visit: "https://www.nitishitp.com/nikobot",
    id: 2,
  },
  {
    title: "Rose light",
    description:
      "Rose light is a physical computing project that is made of 3d printing parts and Arduino. The color is controlled by a smartphone via Bluetooth",
    image: "/images/roselight.webp",
    tags: ["Arduino", "3D printer", "Bluetooth"],
    source: "",
    visit: "",
    id: 3,
  },
  {
    title: "Gif Camera",
    description:
      "Gif Camera is a physical computing prototype. This device offers a function that can create a gif easily to users. This offers 5 types of filters with combinations of three buttons.",
    image: "/images/gifcamera.webp",
    tags: ["Raspberry Pi Zero", "python", "ffmpeg"],
    source: "https://github.com/koji/gifCamera",
    visit: "",
    id: 4,
  },
  {
    title: "RealSense Scan App",
    description:
      "This is an experimental project to use RealSense and openFrameworks.",
    image: "/images/realsense.webp",
    tags: ["Realsense", "openFrameworks", "c++"],
    source: "https://github.com/koji/RealSense",
    visit: "",
    id: 5,
  },
  {
    title: "Ichi-go ichi-e",
    description: `Ichi-go ichi-e is a Japanese four-character idiom.
            The term means "for this time only" or "once in a lifetime."
            Ichi-go ichi-e is an openFrameworks application that generates a new shader code.`,
    image: "/images/ichi-go-ichi-e.webp",
    tags: ["openFrameworks", "FragmentShaders", "python"],
    source: "",
    visit: "https://vimeo.com/363803650",
    id: 6,
  },
  {
    title: "Jobs on GitHub",
    description:
      "Use GitHub API for Job boards with Reactjs and Typescript. The main purpose is to use react hooks.",
    image: "/images/jobs-on-github.webp",
    tags: ["React", "TypeScript", "GitHub API", "Netlify"],
    source: "",
    visit: "https://engineer-job-board.netlify.app/",
    id: 7,
  },
  {
    title: "Movie Search App",
    description:
      "Use OMDB API with Reactjs and Typescript. Currently the website has a search function.",
    image: "/images/movieapp.webp",
    tags: ["React", "TypeScript", "OMDB API", "Netlify"],
    source: "",
    visit: "https://react-movie-list-app.netlify.app/",
    id: 8,
  },
  {
    title: "Instagram Effects",
    description: "Instagram Effects with FragmentShaders",
    image: "/images/instagram.webp",
    tags: ["SparkAR Studio", "JavaScript", "FragmentShaders"],
    source: "",
    visit: "https://www.facebook.com/sparkarhub/portfolios/1305061616534560",
    id: 9,
  },
  {
    title: "NewsAPI News",
    description: "nextjs demo app with News API (SSG)",
    image: "/images/nextjs-with-newsapi.webp",
    tags: ["Nextjs", "TypeScript", "News API", "Vercel"],
    source: "",
    visit: "https://nextjs-with-newsapi.vercel.app/",
    id: 10,
  },
  {
    title: "Math art",
    description: "Generative art that is generated by Julia Sets.",
    image: "/images/math-art.webp",
    tags: ["Processing", "Netlify"],
    source: "",
    visit: "https://math-art.netlify.app/",
    id: 11,
  },
];

export const OSSProjects = [
  {
    title: "easyGAN",
    description:
      "easyGAN is a CLI tool which can train images and generates images with DCGAN.",
    image: "/images/easygan.webp",
    tags: ["python", "keras", ""],
    link: "https://easygan.netlify.app/",
    code: "",
    id: 0,
  },
  {
    title: "icTrainer",
    description:
      "icTrainer is a CLI tool which offers a couple of functions to train own image classifier. It offers image collecting, resize, and face detector.",
    image: "/images/ictrainer.webp",
    tags: ["python", "keras", "tensorflow"],
    link: "https://pypi.org/project/ictrainer/",
    code: "https://github.com/koji/icTrainer",
    id: 1,
  },
  {
    title: "gengitignore",
    description:
      "gengitignore is a CLI tool to generate .gitignore file. This package help developers to manage codes on Git/Github.",
    image: "/images/gengitignore.webp",
    tags: ["nodejs"],
    link: "https://www.npmjs.com/package/@kojikanao/gengitignore",
    code: "https://github.com/koji/genigore",
    id: 2,
  },
  {
    title: "wcartist",
    description:
      "wcartist is a CLI tool which allows users to create word art with one line command.",
    image: "/images/wcartist.webp",
    tags: ["python"],
    link: "https://pypi.org/project/wcartist/",
    code: "https://github.com/koji/wcartist",
    id: 3,
  },
  {
    title: "react-nes-components",
    description:
      "nes-components is a react-component with nes.css. This is published as a npm package.",
    image: "/images/nes-components.webp",
    tags: ["react", "typescript", "storybook", "bit.dev", "Netlify"],
    link: "https://nes-components.netlify.com/",
    code: "https://github.com/koji/react-nes-components",
    id: 4,
  },
  {
    title: "mtrand",
    description: "mtrand is Deno third party module and it's mt19937 for Deno.",
    image: "/images/mtrand.webp",
    tags: ["Deno", "TypeScript", "GitHub Action"],
    link: "https://deno.land/x/mtrand",
    code: "https://github.com/koji/deno-mtrand",
    id: 5,
  },
  {
    title: "p5js-web-editor Japanese UI",
    description: "I led to add Japanese translation to p5js web editor.",
    image: "/images/p5js-web-editor.webp",
    tags: ["javascript", "react", "i18n"],
    link: "https://editor.p5js.org/",
    code: "https://github.com/processing/p5.js-web-editor/releases/tag/v1.2.0",
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2010, text: "Started my journey" },
  { year: 2013, text: "Worked as a freelance developer" },
  { year: 2016, text: "Founded JavaScript Mastery" },
  { year: 2018, text: "Shared my projects with the world" },
  { year: 2019, text: "Started my own platform" },
  { year: 2020, text: "Started my own platform" },
  { year: 2021, text: "Started my own platform" },
];
