export const projects = [
  {
    title: "mtindo",
    description:
      "mtindo is a style transfer application. It offers a unique opportunity that generates a new image/video from an image/video.",
    image: "/images/mtindo.webp",
    tags: ["python", "nodejs", "electron"],
    source: "",
    visit: "https://itp.nyu.edu/thesis2018/#/student/koji",
    id: 0,
  },
  {
    title: "Data from Mukuru",
    description:
      "Data Visualization project with Pawa Initiative which is a NPO in Nairobi, Kenya.",
    image: "/images/data-from.webp",
    tags: ["js", "D3js", "heroku"],
    source: "",
    visit: "http://datavi.herokuapp.com/mukuru/",
    id: 1,
  },
  {
    title: "nikobot",
    description:
      "nikobot is an interactive expressive robot pet for your desk, a minimal interactive robot.",
    image: "/images/nikobot.webp",
    tags: ["Arduino", "html", "css", "js"],
    source: "",
    visit: "https://www.nitishitp.com/nikobot",
    id: 2,
  },
  {
    title: "Rose light",
    description:
      "Rose light is a physical computing project that is made of 3d printing parts and Arduino. The color is controlled by a smartphone via Bluetooth",
    image: "/images/roselight.webp",
    tags: ["Arduino", "3D printer", "Bluetooth"],
    source: "",
    visit: "",
    id: 3,
  },
  {
    title: "Gif Camera",
    description:
      "Gif Camera is a physical computing prototype. This device offers a function that can create a gif easily to users. This offers 5 types of filters with combinations of three buttons.",
    image: "/images/gifcamera.webp",
    tags: ["Raspberry Pi Zero", "python", "ffmpeg"],
    source: "https://github.com/koji/gifCamera",
    visit: "",
    id: 4,
  },
  {
    title: "RealSense Scan App",
    description:
      "This is an experimental project to use RealSense and openFrameworks.",
    image: "/images/realsense.webp",
    tags: ["Realsense", "openFrameworks", "c++"],
    source: "https://github.com/koji/RealSense",
    visit: "",
    id: 5,
  },
  {
    title: "Ichi-go ichi-e",
    description: `Ichi-go ichi-e is a Japanese four-character idiom.
            The term means "for this time only" or "once in a lifetime."
            Ichi-go ichi-e is an openFrameworks application that generates a new shader code.`,
    image: "/images/ichi-go-ichi-e.webp",
    tags: ["openFrameworks", "FragmentShaders", "python"],
    source: "",
    visit: "https://vimeo.com/363803650",
    id: 6,
  },
  {
    title: "Jobs on GitHub",
    description:
      "Use GitHub API for Job boards with Reactjs and Typescript. The main purpose is to use react hooks.",
    image: "/images/jobs-on-github.webp",
    tags: ["React", "TypeScript", "GitHub API", "Netlify"],
    source: "",
    visit: "https://engineer-job-board.netlify.app/",
    id: 7,
  },
  {
    title: "Movie Search App",
    description:
      "Use OMDB API with Reactjs and Typescript. Currently the website has a search function.",
    image: "/images/movieapp.webp",
    tags: ["React", "TypeScript", "OMDB API", "Netlify"],
    source: "",
    visit: "https://react-movie-list-app.netlify.app/",
    id: 8,
  },
  {
    title: "Instagram Effects",
    description: "Instagram Effects with FragmentShaders",
    image: "/images/instagram.webp",
    tags: ["SparkAR Studio", "JavaScript", "FragmentShaders"],
    source: "",
    visit: "https://www.facebook.com/sparkarhub/portfolios/1305061616534560",
    id: 9,
  },
  {
    title: "NewsAPI News",
    description: "nextjs demo app with News API (SSG)",
    image: "/images/nextjs-with-newsapi.webp",
    tags: ["Nextjs", "TypeScript", "News API", "Vercel"],
    source: "",
    visit: "https://nextjs-with-newsapi.vercel.app/",
    id: 10,
  },
  {
    title: "Math art",
    description: "Generative art that is generated by Julia Sets.",
    image: "/images/",
    tags: ["Processing", "Netlify"],
    source: "",
    visit: "math-art.webp",
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2017, text: "Started my journey" },
  { year: 2018, text: "Worked as a freelance developer" },
  { year: 2019, text: "Founded JavaScript Mastery" },
  { year: 2020, text: "Shared my projects with the world" },
  { year: 2021, text: "Started my own platform" },
];
